name: Docker Image CI
on:
  push:
    branches:
    - master
    - gh-actions
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/docker/cli@master
    - name: Build the Docker image
      run: docker build -t robertd/alpine-terraform .
